data_sanitize_menu:
    path: /menu
    controller: Endroid\DataSanitizeBundle\Controller\MenuController

data_sanitize_list:
    path: /{name}
    controller: Endroid\DataSanitizeBundle\Controller\ListController

data_sanitize_merge:
    path: /{name}/merge
    controller: Endroid\DataSanitizeBundle\Controller\MergeController

data_sanitize_state:
    path: /{name}/state
    controller: Endroid\DataSanitizeBundle\Controller\StateController
