services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\DataSanitizeBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Endroid\DataSanitizeBundle\Command\SanitizeCommand: ~
    Endroid\DataSanitize\RelationFinder: ~
    Endroid\DataSanitize\SanitizerFactory: ~
    Endroid\DataSanitizeBundle\Configuration: ~
